version: '3.3'

services:

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'db-biometric'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'

  app:
    image: 'authentication_api'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 888:888
    depends_on:
      - db